### PR TITLE
Port to libav 10 API

### PR DESCRIPTION
**Pull request by phako**
Remove deprecated definitions and struct members

### CODE REVIEW

**Comment by barbieri** [comment]
Hi phako,

I'm on a trip and I'll be able to check this only next week. I wonder if this patch will require too recent libav/ffmpeg, if so do you know how many distros package it already? If it's too new we'll have to add some #ifdef and detect the version at compile time.

@dorileo  can you take a look while I'm traveling?

**Comment by phako** [comment]
I think the 10 API only removed things that were deprecated for some time. I can try to find out where those things were introduced. If I got it correctly, if you have the other AV_CODEC_* constants you should also have AV_CODEC_ID_MP3 and avg_bitrate seems to have been there and usable for quite some time as well.

**Comment by dorileo** [comment]
I'll take a look at ASAP....

**Comment by dorileo** [comment]
@barbieri , The libav 10 is been around for quite some time now (first released in 2009), also for tizen packaging we've maintained a patch doing exactly the same thing the phako's does.

Having said that, I think it's totally fine to merge this patch.

**Pull request merged**
